---
- name: Pure Storage LB example
  hosts: localhost
  gather_facts: no
  collections:
    - purestorage.flasharray
  vars:
    array_usage: []
    ansible_python_interpreter: /usr/bin/python3
  roles:
    - role: lb

  tasks:
    - name: Provisioning {{ use_name }}
      purefa_volume:
        fa_url: "{{ use_url }}"
        api_token: "{{ use_api }}"
        name: lbtest01
        size: 50G
