---
- name: Pure Storage LB example
  hosts: localhost
  gather_facts: no
  vars:
    array_usage: []
  roles:
    - role: lb

  tasks:
    - name: Provisioning {{ use_name }}
      purefa_volume:
        fa_url: "{{ use_url }}"
        api_token: "{{ use_api }}"
        name: lbtest01
        size: 50G
